# Generated by Django 5.2.1 on 2025-07-07 19:56

import myapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30, validators=[myapp.validators.validate_name])),
                ('lastName', models.CharField(max_length=20, validators=[myapp.validators.validate_name])),
                ('email', models.EmailField(max_length=254)),
                ('college', models.CharField(max_length=70, validators=[myapp.validators.validate_college])),
                ('department', models.CharField(max_length=35)),
                ('yearOfStudy', models.CharField(max_length=4)),
                ('phone', models.CharField(validators=[myapp.validators.validate_phone])),
                ('password', models.CharField(validators=[myapp.validators.validate_strong_password])),
                ('cnfrmPassword', models.CharField()),
            ],
        ),
    ]
