# Generated by Django 5.2.1 on 2025-07-07 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cnfrmPassword',
        ),
    ]
