# Generated by Django 5.2.1 on 2025-07-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_student_cnfrmpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competetions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('status', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(),
        ),
    ]
