# Generated by Django 5.2.1 on 2025-08-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_competetions_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competetions',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
