# Generated by Django 5.2.1 on 2025-08-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_competetions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='competetions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='competition_images/'),
        ),
    ]
