# Generated by Django 5.2.1 on 2025-08-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_competetions_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competetions',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='competition_images/'),
        ),
    ]
