# Generated by Django 5.2.1 on 2025-07-05 08:06

import django.core.validators
import myapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=30)),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[myapp.validators.only_positive])),
                ('p_details', models.CharField(max_length=100)),
                ('p_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
